spring:
  application:
    name: stream_recorder
  datasource:
    url: jdbc:sqlite:data/recorder.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  quartz:
    job-store-type: memory

app:
  security:
    # (at least 256 bits/32 characters)
    jwt-secret: ht5d8sg12-oap57as7-25874snh-p8hhh6vf