spring:
  application:
    name: stream_recorder
  datasource:
    url: jdbc:sqlite:data/recorder.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  quartz:
    job-store-type: memory